### ISSUE TITLE
Looking forward to participating in this project ヾ(◍°∇°◍)ﾉﾞ ~

### ISSUE THREAD

**Issue by GoogTech** [lycodestore/dbhelper#1]
:smiley: *你好哟,我是一名大二学生,今天看到你这个项目蛮感动的,觉的非常赞 !  但是自己并没有接触过`Vue`,不过目前正在学习如何使用它,期待与你的合作嘿嘿~*

**Comment by lycodestore** [comment]
我本人也是一名大学生本科生，非常感谢你的赞赏！

**Comment by lycodestore** [comment]
目前这个版本是我练手的时候做出来的，项目整体规划做得并不是很好，我正在构思第二版的架构，后续如果你有兴趣，非常欢迎你的加入！

**Comment by GoogTech** [comment]
非常乐意哟,很期待你的想法  !
